version: 2
jobs:
  build:
    docker:
      - image: oyinloslos/nodebase:latest
        environment:
          DATABASE_URL: mongodb://localhost/note
      - image: mongo
    steps:
      - checkout
      - run: npm install
      - run: npm test

deployment:
  staging:
    branch: master
    heroku:
      appname: scribblenoteapp